---
- name: configure ZFS kernel parameters
  template:
    src: etc/modprobe.d/zfs.conf.j2
    dest: /etc/modprobe.d/zfs.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - update initramfs (Debian)
    - mkinitcpio (Arch Linux)

- name: configure ZFS
  template:
    src: etc/default/zfs.j2
    dest: /etc/default/zfs
    owner: root
    group: root
    mode: 0644

- block:
    - name: get serial of devices
      command: "udevadm info -q property {{ item }}"
      failed_when: false
      register: device_properties
      loop: "{{ zfs_config_none_ioscheduler }}"

    - name: set IO scheduler of HDDs to 'none'
      template:
        src: etc/udev/rules.d/90-zfs-io-scheduler.rules.j2
        dest: /etc/udev/rules.d/90-zfs-io-scheduler.rules
        mode: 0644
      notify: reload udev rules
