---
- name: get list of available zpools
  ansible.builtin.shell: "set -o pipefail; zpool list | awk 'FNR >1' | awk '{print $1}'"
  args:
    executable: /bin/bash
  register: available_zpools
  changed_when: false
  check_mode: false

- name: get list of importable zpools
  ansible.builtin.shell: "set -o pipefail; zpool import | sed -nr 's/^\\s*pool: (.*)/\\1/p'"
  args:
    executable: /bin/bash
  register: importable_zpools
  changed_when: false
  check_mode: false

- name: include single pool management tasks
  ansible.builtin.include_tasks: manage_pool.yml
  vars:
    zfs_pool: "{{ zfs_pools_defaults | combine(_zfs_pool) }}"
    zfs_dataset_properties: "{{
        zfs_filesystems_properties_defaults |
        combine(zfs_pool.filesystem_properties |
        default({}))
      }}"
  loop: "{{ zfs_pools }}"
  loop_control:
    loop_var: _zfs_pool
